package:
  name: test8
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test8", max_pin=None) }}

requirements:
  run:
    - test3 >=1.0

test:
  commands:
    - ls
about:
  license: MIT
  summary: test8
  home: https://bioconda.gitub.io
