{% set name = "blobtk" %}
{% set version = "0.7.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/genomehubs/blobtk/archive/{{ version }}.tar.gz
  sha256: 9e66ce172456339879670602e864859b70303a4d7c85fa508038b8f81026c63b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('blobtk', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - clangdev
    - llvmlite
    - pkg-config
  host:
    - python
    - pip
    - maturin
    - curl
    - wget
    - openssl
    - zlib
  run:
    - python

test:
  imports:
    - blobtk
  commands:
    - blobtk --help

about:
  home: "https://github.com/genomehubs/blobtk"
  summary: "Core functionality shared across BlobToolKit tools."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://github.com/genomehubs/blobtk"
  doc_url: "https://github.com/genomehubs/blobtk/wiki"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
