{% set name = "samap" %}
{% set version = "1.0.16" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "61d68f708af8cb1dadbf70aa9afe672016af7f93a580b08a8d9c7b7d9c75b9fd"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python <3.8
  run:
    - dill
    - h5py <=2.10
    - hnswlib
    - leidenalg
    - python <3.8
    - sam-algorithm >=0.8.4
    - scanpy

test:
  imports:
    - samap
    - samap.mapping
    - samap.analysis

about:
  home: "https://github.com/atarashansky/SAMap"
  license: "MIT"
  license_family: "MIT"
  summary: "The SAMap algorithm"

extra:
  recipe-maintainers:
    - atarashansky
    - pinin4fjords
