{% set name = "perl-test-files" %}
{% set version = "0.17" %}
{% set sha256 = "1587ad97ccaebdbde70b2ca275f45d49a28b2660ebacc7ebf19440ce217c5826" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/J/JS/JSF/Test-Files-0.17.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
    - perl
    - perl-text-diff
    - perl-test-builder-tester
    - perl-algorithm-diff

  run:
    - perl
    - perl-text-diff
    - perl-test-builder-tester
    - perl-algorithm-diff

test:
  imports:
    - Test::Files

about:
  home: http://metacpan.org/pod/Test::Files
  license: unknown
  summary: 'A Test::Builder based module to ease testing with files and dirs'
