{% set name = "perl-test-files" %}
{% set version = "0.16" %}
{% set sha256 = "75b9319725b81e913734658bac4883686b5624362cf2cadda3fd726238d8cdbd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/J/JS/JSF/Test-Files-0.16.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
    - perl
    - perl-text-diff
    - perl-test-builder-tester
    - perl-algorithm-diff

  run:
    - perl
    - perl-text-diff
    - perl-test-builder-tester
    - perl-algorithm-diff

test:
  imports:
    - Test::Files

about:
  home: http://metacpan.org/pod/Test::Files
  license: unknown
  summary: 'A Test::Builder based module to ease testing with files and dirs'
