{% set name = "perl-test-files" %}
{% set version = "0.23" %}
{% set sha256 = "7b9a29bd5f80f5928dcb15903ecb726fac4d0fbc5e4e0aae589a7ccb3d5acc17" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/J/JS/JSF/Test-Files-0.23.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('perl-test-files', max_pin="x.x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-file-copy-recursive
    - perl-findbin
    - perl-test-simple
    - perl-text-diff
  run:
    - perl
    - perl-text-diff
    - perl-const-fast
    - perl-exporter
    - perl-fcntl
    - perl-padwalker
    - perl-path-tiny >=0.144

test:
  imports:
    - Test::Files

about:
  home: https://metacpan.org/pod/Test::Files
  license: unknown
  summary: 'A Test::Builder based module to ease testing with files and dirs'
