{% set name = "perl-test-files" %}
{% set version = "0.22" %}
{% set sha256 = "b5345622657052340463639d8b045f1e5cbecdb5d06d0079c62b57d016f49ee0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/J/JS/JSF/Test-Files-0.22.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('perl-test-files', max_pin="x.x") }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-file-copy-recursive
    - perl-findbin
    - perl-test-simple
    - perl-text-diff
  run:
    - perl
    - perl-text-diff
    - perl-const-fast
    - perl-exporter
    - perl-fcntl
    - perl-padwalker
    - perl-path-tiny >=0.144

test:
  imports:
    - Test::Files

about:
  home: https://metacpan.org/pod/Test::Files
  license: unknown
  summary: 'A Test::Builder based module to ease testing with files and dirs'
