package:
  name: test4
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test4", max_pin=None) }}

test:
  commands:
    - ls
about:
  license: MIT
  summary: test4
  home: https://bioconda.gitub.io
