{% set version = "0.3.5" %}

package:
  name: vcfexpress
  version: {{ version }}

build:
  number: 0
  skip: true  # [osx]
  run_exports:
    - {{ pin_subpackage('vcfexpress', max_pin="x.x") }}

source:
  url: https://github.com/brentp/vcfexpress/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 619164dd3909c2010eb406b9a01f7034069d60e177a22378b4339f1766a29be7

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    - clangdev
    - cmake
    - make

test:
  commands:
    - vcfexpress --help

about:
  home: https://github.com/brentp/vcfexpress/
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: expressions on VCFs

extra:
  additional-platforms:
    - linux-aarch64
