{% set name = "nanocompore" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 902b13332438e49a44c7a16d4ce4437b156973078e6c983fe2adbc337259aeb0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  entry_points:
    - nanocompore = nanocompore.__main__:main
  run_exports:
    - {{ pin_subpackage('nanocompore', max_pin="x") }}

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - gtfparse >=2.5.0
    - jaxtyping >=0.2.38
    - matplotlib-base
    - numpy <2.0
    - pandas
    - pynvml >=12.0.0
    - pyfaidx
    - pysam >=0.22.0
    - python >=3.10
    - pyyaml
    - schema >=0.7.5
    - scikit-learn >=1.4
    - scipy >=1.15
    - seaborn-base
    - statsmodels >=0.14
    - tqdm
    - bedparse
    - importlib_metadata
    - loguru

test:
  commands:
    - nanocompore sampcomp --help
    - nanocompore simreads --help

about:
  home: "https://github.com/tleonardi/nanocompore"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "Nanocompore identifies raw signal changes between two conditions from dRNA-Seq data."
  dev_url: "https://github.com/tleonardi/nanocompore"
  doc_url: "https://nanocompore.rna.rocks"

extra:
  recipe-maintainers:
    - bgruening
  identifiers:
    - usegalaxy-eu:nanocompore_db
