package:
  name: test12
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test12", max_pin=None) }}

requirements:
  run:
    - test6 >=1.0
 
test:
  commands:
    - ls
about:
  license: MIT
  summary: test12
  home: https://bioconda.gitub.io
