{% set name = "perl-sys-info-base" %}
{% set version = "0.7809" %}
{% set sha256 = "c1bd2b7423d923bb0bfdd0afbd4c5ec28d6af90d32f621dd06773a14436ce3b2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BU/BURAK/Sys-Info-Base-{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - make
    - perl
    - perl-extutils-makemaker
    - perl-text-template-simple
  run:
    - perl
    - perl-text-template-simple
    - perl-parent 
    - perl-sys-hostip 

test:
  imports:
    - Sys::Info::Base

about:
  home: "https://metacpan.org/pod/Sys::Info::Base"
  license: "Perl_5"
  summary: "Base class for Sys::Info"
  doc_url: "https://metacpan.org/pod/Sys::Info::Base"

extra:
  recipe-maintainers:
    - xileF1337
