{% set name = "perl-sys-info-base" %}
{% set version = "0.7808" %}
{% set sha256 = "da2b5b326b605932045a21f08d7949efb69e9f730048ecd49972f505fde203a3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BU/BURAK/Sys-Info-Base-{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
    - perl
    - perl-extutils-makemaker
    - perl-text-template-simple
  run:
    - perl
    - perl-text-template-simple
    - perl-parent 
    - perl-sys-hostip 

test:
  imports:
    - Sys::Info::Base

about:
  home: http://metacpan.org/pod/Sys::Info::Base
  license: perl_5
  summary: 'Base class for Sys::Info'

extra:
  recipe-maintainers:
    - xileF1337
