{% set name = "RecGraph" %}
{% set version = "1.0.1" %}
{% set sha256 = "cf5c462aa81bfdc1bbeefb15ee11f7e9b5868a867f6564e8fcee26a8507ef087" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AlgoLab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - rust =1.74

test:
  commands:
    - recgraph --help

about:
  home: https://github.com/AlgoLab/{{ name }}
  license: MIT
  license_file: LICENSE
  summary: Optimal sequence-to-graph alignment with recombinations

extra:
  recipe-maintainers:
    - yp
