{% set version = "1.5.8" %}
{% set name = "grepq" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Rbfinch/{{ name }}/archive/refs/tags/{{ name }}-v{{ version }}.tar.gz
  sha256: 561ba8c0f18ba8e086bf9919a163537812fa3f31ca4854ac114db496c126d70e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('grepq', max_pin="x") }}
  script:
    - export CFLAGS="${CFLAGS} -O3 -I${PREFIX}/include -Wno-implicit-function-declaration"
    - export CXXFLAGS="${CXXFLAGS} -O3 -I${PREFIX}/include"
    - export LDFLAGS="${LDFLAGS} -L${PREFIX}/lib"
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install -v --no-track --root "${PREFIX}" --path .

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - pkg-config
  host:
    - sqlite
    - zstd
    
test:
  commands:
    - grepq --version
    - grepq --help

about:
  home: "https://github.com/Rbfinch/grepq"
  license: MIT  # please use https://spdx.org identifiers
  license_family: MIT
  license_file:
    - LICENSE.md         # the license file for your package
    - THIRDPARTY.yml     # this file is generated by cargo-bundle-licenses
  summary: "Quickly filter FASTQ files."
  dev_url: "https://github.com/Rbfinch/grepq"
  doc_url: "https://github.com/Rbfinch/grepq/blob/grepq-v{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - Rbfinch
  identifiers:
    - doi:10.5281/zenodo.14031703
