{% set name = 'hail' %}
{% set version = '0.2.127' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/hail-is/hail.git
  git_rev: {{ version }}
  sha256: unused

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("hail", max_pin="x.x") }}

# Refer to these files for version pinning:
# - 'hail/python/requirements.txt'
# - 'hail/python/hailtop/requirements.txt'
# - 'hail/web_common/requirements.txt'

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - rsync
  host:
    - lz4
    - openjdk 8.*
    - pip
    - pyspark >=3.3.2,<3.4
    - pytest-runner
    - python
  run:
    - python
    # ==========================================================================
    # Deps in 'hail/python/requirements.txt':
    # ==========================================================================
    - avro >=1.10,<1.12
    - bokeh >=3,<4
    - decorator <5
    - deprecated >=1.2.10,<1.3
    - numpy <2
    - pandas >=2,<3
    - parsimonious <1
    - plotly >=5.18.0,<6
    - protobuf  # ==3.20.2
    - pyspark >=3.3.2,<3.4
    - requests >=2.31.0,<3
    - scipy >1.2,<1.12
    # ==========================================================================
    # Deps in 'hail/python/hailtop/requirements.txt':
    # ==========================================================================
    - aiodns >=2.0.0,<3
    - aiohttp >=3.9,<4
    - azure-identity >=1.6.0,<2
    - azure-mgmt-storage ==20.1.0
    - azure-storage-blob >=12.11.0,<13
    - boto3 >=1.17,<2.0
    - botocore >=1.20,<2.0
    - dill >=0.3.6,<0.4
    - frozenlist >=1.3.1,<2
    - google-auth >=2.14.1,<3
    - google-auth-oauthlib >=0.5.2,<1
    - humanize >=4.0,<5   # using updated pin from 0.2.133 release
    - janus >=0.6,<1.1
    - nest-asyncio >=1.5.8,<2  # pip: nest_asyncio
    - orjson >=3.6.4,<4
    # > - protobuf ==3.20.2
    - rich >=12.6.0,<13
    - typer >=0.9.0,<1
    - python-json-logger >=2.0.2,<3
    - pyyaml >=6.0,<7.0
    - sortedcontainers >=2.4.0,<3
    - tabulate >=0.8.9,<1
    - uvloop >=0.19.0,<1  # not win32?
    - jproperties >=2.1.1,<3
    # ==========================================================================
    # Deps in 'web_common/requirements.txt':
    # ==========================================================================
    - aiohttp-jinja2 >=1.1.1,<2
    - jinja2 >3,<4  # pip: Jinja2
    - libsass >=0.19.2,<1
    # ==========================================================================
    # Deps in 'hail/python/test/hailtop/hailctl/dataproc/conftest.py':
    # ==========================================================================
    # > - aiohttp >=3.6,<3.7
    - aiohttp-session >=2.7,<2.8  # pip: aiohttp_session
    - asyncinit >=0.2.4,<0.3
    # > - bokeh >1.1,<1.3
    # > - decorator <5
    # > - humanize ==1.0.0
    - hurry.filesize ==0.9
    # > - nest_asyncio
    # > - numpy <2
    # > - pandas >0.24,<0.26
    # > - parsimonious <0.9
    - pyjwt  # pip: PyJWT
    # > - python-json-logger ==0.1.11
    # > - requests >=2.21.0,<2.21.1
    # > - scipy >1.2,<1.4
    # > - tabulate ==0.8.9
    - tqdm  # ==4.42.1
    # > - jproperties==2.1.1
    # ==========================================================================
    # Other deps previously defined:
    # ==========================================================================
    - gcsfs
    - google-api-core
    - google-cloud-sdk
    - google-cloud-storage
    - openjdk 8.*

test:
  imports:
    - hail
    - hailtop.batch

about:
  home: https://hail.is
  dev_url: https://github.com/hail-is/hail
  license: MIT
  license_file: LICENSE
  summary: |
    Hail is Python-based data analysis tool for working with genomic data.

extra:
  skip-lints:
    - uses_vcs_url
  recipe-maintainers:
    - raivivek
    - mjsteinbaugh
