package:
  name: _test-pkg_format-2
  version: 1.0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("_test-pkg_format-2", max_pin="x") }}
  script: touch "${PREFIX}/test-file"

requirements:
  build:
    - {{ compiler("c") }}

test:
  commands:
    - test -f "${PREFIX}/test-file"

about:
  home: https://bioconda.github.io
  dev_url: https://github.com/bioconda/bioconda-recipes
  doc_url: https://bioconda.github.io
  license: ISC
  summary: Testing .conda package format

extra:
  recipe-maintainers:
    - mbargull
