package:
  name: test6
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test6", max_pin=None) }}

run:
  - test1 >= 1.0
  - test2 >= 1.0

test:
  commands:
    - ls
about:
  license: MIT
  summary: test6
  home: https://bioconda.gitub.io
