package:
  name: test7
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test7", max_pin=None) }}

requirements:
  run:
    - test2 >=1.0

test:
  commands:
    - ls
about:
  license: MIT
  summary: test7
  home: https://bioconda.gitub.io
