package:
  name: test9
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test9", max_pin=None) }}

requirements:
  run:
    - test3 >= 1.0

test:
  commands:
    - ls
about:
  license: MIT
  summary: test9
  home: https://bioconda.gitub.io
