{% set name = "aspera-cli" %}
{% set version = "4.21.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: https://github.com/IBM/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: c2113e350561ba62eea382ce579680f32af548f919985626ab0c108ca283d85b

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('aspera-cli', max_pin="x") }}

requirements:
  host:
    - ruby >=3
    - make
  run:
    - ruby >=3

test:
  commands:
    - ascli -h

about:
  home: "https://github.com/IBM/aspera-cli"
  license: "Apache-2.0"
  license_file: LICENSE
  license_family: APACHE
  summary: "Command Line Interface for IBM Aspera products."
  dev_url: "https://github.com/IBM/aspera-cli"
  doc_url: "https://www.rubydoc.info/gems/aspera-cli"

extra:
  recipe-maintainers:
    - farchaab
