{% set name = "aspera-cli" %}
{% set version = "4.24.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: https://github.com/IBM/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 8e91e721ac698e9aae816d3707e6e7afc5fe46b5f0ae5148d5af7b9867e56f52

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('aspera-cli', max_pin="x") }}

requirements:
  host:
    - ruby >=3
    - make
  run:
    - ruby >=3

test:
  commands:
    - ascli -h

about:
  home: "https://github.com/IBM/aspera-cli"
  license: "Apache-2.0"
  license_file: LICENSE
  license_family: APACHE
  summary: "Command Line Interface for IBM Aspera products."
  dev_url: "https://github.com/IBM/aspera-cli"
  doc_url: "https://www.rubydoc.info/gems/aspera-cli"

extra:
  recipe-maintainers:
    - farchaab
