{% set name = "aspera-cli" %}
{% set version = "4.24.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: https://github.com/IBM/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 63cc665e80135fa140ba64c2c14e72c695ba6ccfce002f7d7ff1172f2d8e4c79

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('aspera-cli', max_pin="x") }}

requirements:
  host:
    - ruby >=3
    - make
  run:
    - ruby >=3

test:
  commands:
    - ascli -h

about:
  home: "https://github.com/IBM/aspera-cli"
  license: "Apache-2.0"
  license_file: LICENSE
  license_family: APACHE
  summary: "Command Line Interface for IBM Aspera products."
  dev_url: "https://github.com/IBM/aspera-cli"
  doc_url: "https://www.rubydoc.info/gems/aspera-cli"

extra:
  recipe-maintainers:
    - farchaab
