{% set version = "1.14.0" %}

package:
  name: orthanq
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('orthanq', max_pin="x") }}

source:
  url: https://github.com/orthanq/orthanq/archive/v{{ version }}.tar.gz
  sha256: ea441de07e135639797a55e66d8c4db55692de35c9068b73080489d0f26da560

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config
    - make
    - cmake
    - perl-findbin
    # datavzrd dependencies
    - python >=3.10
    - nodejs
    - pnpm
    - clangdev
  host:
    - gsl
    - libcblas
    - openssl  # [not osx]
    - zlib
    - bzip2
    - xz
    - coincbc
    - fontconfig
    - htslib
    - varlociraptor ==8.4.7
    - samtools ==1.19
    - vg ==1.63.1
    - minimap2
    - bwa
  run:
    - python >=3.10
    - gsl
    - openssl
    - coincbc
    - fontconfig
    - yte

test:
  commands:
    - orthanq -h

about:
  home: "https://github.com/orthanq/orthanq"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Uncertainty aware HLA typing and general haplotype quantification."
  dev_url: "https://github.com/orthanq/orthanq"

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
