{% set version = "0.14.0" %}
{% set sha256 = "e483535cf2691b094b4121e58d539cb8a953b0b0b63339ea10ef7d81ce79008b" %}

package:
  name: vcfpy
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/v/vcfpy/vcfpy-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  run_exports:
    - {{ pin_subpackage('vcfpy', max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pysam >=0.10.0

test:
  imports:
    - vcfpy

about:
  home: https://github.com/bihealth/vcfpy
  license: MIT
  license_family: MIT
  summary: Python 3 VCF library with good support for both reading and writing
