package:
  name: test15
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test15", max_pin=None) }}

requirements:
  run:
    - test12 >= 1.0

test:
  commands:
    - ls
about:
  license: MIT
  summary: test15
  home: https://bioconda.gitub.io
