{% set name = "MentaLiST" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WGS-TB/MentaLiST/archive/v{{ version }}.tar.gz
  sha256: 6cc0ff1f39e892b0a5c71e6d477404c6b72d368ab3436146248419d59863eb48

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mentalist', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    # We can't use julia=0.6 because that Conda package appears to be broken.
    - julia
    - hdf5
    - mpfr 3.1.5.*
  run:
    - julia
    - hdf5
    - mpfr 3.1.5.*
    - libxml2
    - unzip

test:
  commands:
    - mentalist -h

about:
  home: "https://github.com/WGS-TB/MentaLiST"
  summary: "The MLST pipeline developed by the PathOGiST research group."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://github.com/WGS-TB/MentaLiST"
  doc_url: "https://github.com/WGS-TB/MentaLiST/blob/v{{ version }}/README.md"

extra:
  skip-lints:
    - should_be_noarch_generic
  identifiers:
    - biotools:mentalist
