package:
  name: test3
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test3", max_pin=None) }}

test:
  commands:
    - ls
about:
  license: MIT
  summary: test3
  home: https://bioconda.gitub.io
