package:
  name: test5
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test5", max_pin=None) }}

run:
  - test15 >= 1.0
  - test8 >= 1.0
  - test10 >= 1.0

test:
  commands:
    - ls
about:
  license: MIT
  summary: test5
  home: https://bioconda.gitub.io
 