{% set name = "gentropy" %}
{% set version = "2.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 789a4f51c8d4b119c626d735a0edfb37e78bb3303f8f897b21e478190b4eeab2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv"
  run_exports:
    - {{ pin_subpackage('gentropy', max_pin="x.x") }}

# Refer to pyproject.toml file for version pinning.

requirements:
  host:
    - pip
    - python >=3.10,<3.11
  run:
    - python >=3.10,<3.11
    - pyspark ==3.3.4
    - scipy >=1.11.4,<1.12.0
    - hydra-core >=1.3.2,<1.4.0
    - pyliftover >=0.4,<0.5
    - numpy >=1.26.2,<1.27.0
    - hail ==0.2.127
    - wandb >=0.19.0,<0.20.0
    - googlesearch >=3.0.0,<3.1.0  # pip: google
    - omegaconf >=2.3.0,<2.4.0
    - typing-extensions >=4.9.0,<4.13.0
    - scikit-learn >=1.6.0,<1.7.0
    - pandas >=2.2.2,<2.3.0
    - skops >=0.11,<0.12
    - google-cloud-secret-manager >=2.20.0,<2.22.0
    - shap >=0.46.0,<0.47.0
    - matplotlib-base >=3.7.3,<3.8.0

test:
  imports:
    - gentropy
  commands:
    - gentropy --version

about:
  dev_url: "https://github.com/opentargets/gentropy"
  home: "https://opentargets.github.io/gentropy/"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: "Open Targets python framework for post-GWAS analysis"

extra:
  recipe-maintainers:
    - mjsteinbaugh
