{% set name = "perl-ipc-shareable" %}
{% set version = "1.13" %}
{% set sha256 = "456e665f72a3fb7ba5a8e70e321cfc9c8259defb3111b51940ad08cab9c00e6b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/ST/STEVEB/IPC-Shareable-1.13.tar.gz
  sha256: {{ sha256 }}

build:
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  number: 7

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

  host:
    - perl
    - perl-extutils-makemaker

  run:
    - perl

test:
  imports:
    - IPC::Shareable

about:
  home: http://metacpan.org/pod/IPC::Shareable
  license: perl_5
  summary: 'IPC::Shareable - Use shared memory backed variables across processes'

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
