{% set version = "0.1.2" %}
{% set commit = "29a6d5c10294c30aec5af5297037f9ef5f28e0ce" %}
{% set sha256 = "6f014018b87cd6db9d72ea2e521c4c198d38910991b0c4a5b7cf4537e60ace10" %}

package:
  name: ligandmpnn
  version: '{{ version }}'

source:
  # NOTE We can change back to Markujsommer/LigandMPNN once this PR is merged:
  # https://github.com/Markusjsommer/LigandMPNN/pull/1
  # and ultimately to dauparas/LigandMPNN if this PR is merged:
  # https://github.com/dauparas/LigandMPNN/pull/45
  url: https://github.com/prihoda/LigandMPNN-fork/archive/{{ commit }}.tar.gz
  sha256: '{{ sha256 }}'
  run_exports:
    - {{ pin_subpackage("ligandmpnn", max_pin="x") }}

build:
  noarch: python
  number: 0
  entry_points:
    - ligandmpnn = ligandmpnn.run:main
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps --no-cache-dir -vvv

requirements:
  host:
    - python >=3.11,<3.12 # restriction in setup.py, can be lifted later
    - pip
    - setuptools
  run:
    - pytorch ==2.3.0
    - biopython ==1.79
    - filelock ==3.13.1
    - fsspec ==2024.3.1
    - Jinja2 ==3.1.3
    - MarkupSafe ==2.1.5
    - mpmath ==1.3.0
    - networkx ==3.2.1
    - numpy ==1.26.4
    - ProDy ==2.4.1
    - ml-collections
    - dm-tree

test:
  imports:
    - ligandmpnn
  files:
    - test.pdb
  commands:
    - ligandmpnn --help
    - |
      ligandmpnn \
        --seed 111 \
        --pdb_path test.pdb \
        --out_folder "outputs/default" \
        --pack_side_chains 1 \
        --number_of_packs_per_design 1 \
        --repack_everything 1
      grep ATOM outputs/default/packed/test_packed_1_1.pdb

about:
  home: "https://github.com/dauparas/LigandMPNN"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "LigandMPNN protein sequence design with pre-trained models included"
  dev_url: https://github.com/Markusjsommer/LigandMPNN
