{% set name = "snakemake-executor-plugin-azure-batch" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snakemake_executor_plugin_azure_batch-{{ version }}.tar.gz
  sha256: 9f828b2c0fa1b62b7160b8790894d325ffda58adec029118a39ad8f677b9a89a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  host:
    - python >=3.11,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.11.0,<4.0.0
    - snakemake-interface-common >=1.17.2,<2.0.0
    - snakemake-interface-executor-plugins >=9.2.0,<10.0.0
    - azure-storage-blob >=12.20.0,<13.0.0
    - azure-batch >=14.2.0,<15.0.0
    - azure-mgmt-batch >=17.0.0,<18.0.0
    - azure-identity >=1.17.1,<2.0.0
    - msrest >=0.7.1,<0.8.0

test:
  imports:
    - snakemake_executor_plugin_azure_batch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snakemake/snakemake-executor-plugin-azure-batch
  summary: A Snakemake executor plugin for submitting jobs to Microsoft Azure Batch.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/snakemake/snakemake-executor-plugin-azure-batch

extra:
  recipe-maintainers:
    - koesterlab
