package:
  name: test11
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test11", max_pin=None) }}

requirements:
  run:
    - test9 >= 1.0
    - test4 >= 1.0

test:
  commands:
    - ls
about:
  license: MIT
  summary: test11
  home: https://bioconda.gitub.io
