package:
  name: test10
  version: 1.0

build:
  noarch: generic
  number: 0
  run_exports: {{ pin_subpackage("test10", max_pin=None) }}

run:
  - test9 >= 1.0

test:
  commands:
    - ls
about:
  license: MIT
  summary: test10
  home: https://bioconda.gitub.io
