{% set name = "EDTA" %}
{% set version = "2.2.0" %}
{% set sha256 = "3515667804437f749f0bb934812ca83b23ec5472c221786f6e5a0d4b613a1a7a" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/oushujun/EDTA/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('edta', max_pin='x') }}

requirements:
  run:
    - annosine2
    - bedtools
    - biopython
    - blast ==2.10.1
    - cd-hit
    - coreutils
    - genericrepeatfinder
    - genometools-genometools
    - glob2
    - h5py >3
    - hmmer
    - irfinder
    - keras
    - ltr_finder
    - ltr_retriever
    - repeatmodeler
    - matplotlib
    - mdust
    - multiprocess
    - muscle
    - nodejs
    - openjdk
    - pandas
    - perl
    - perl-text-soundex
    - python >=3.8
    - r-base 
    - r-ggplot2 
    - r-dplyr 
    - r-tidyr 
    - r-here
    - regex
    - repeatmodeler
    - scikit-learn
    - swifter
    - tensorflow  
    - tesorter    

test:
  commands:
    - EDTA.pl -h > /dev/null
    - EDTA.pl --check_dependencies > /dev/null
    - EDTA_processI.pl -h 2>&1 | grep -i "Perform EDTA"
    - EDTA_raw.pl -h 2>&1 | grep -i "Obtain raw"
    - lib-test.pl -h 2>&1 | grep -i "To test"

about:
  home: https://github.com/oushujun/EDTA
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Extensive de-novo TE Annotator
  dev_url: https://github.com/oushujun/EDTA
