{% set version = "1.5.2" %}
{% set sha256 = "5e5df9686204932802e3f8cabe58121cce629d55dad98efbb6a7bd81bdc5891f" %}

package:
  name: tabixpy
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/t/tabixpy/tabixpy-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage('tabixpy', max_pin="x.x") }}

requirements:
  host:
    - pip
    - setuptools
    - wheel
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - tabixpy
  commands:
    - tabixpy --help
    - tabixpy --version

about:
  home: https://github.com/bejobioinformatics/tabixpy
  license: MIT
  license_family: MIT
  summary: Tabix reader written 100% in Python

extra:
  recipe-maintainers:
    - holtgrewe
