{% set name = "longphase" %}
{% set version = "1.5.2" %}
{% set sha256 = "0cb40d36ce7ac941cbd2f60ac0d0d708995a48b5cb04ed3a9a6c3cc63d35a75a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/twolinin/longphase/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: False  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  run:
    - htslib

test:
  commands:
    - strling -h
    - strling-outliers.py -h

about:
  home: https://github.com/quinlan-lab/STRling
  license: MIT
  summary: STRling (pronounced like “sterling”) is a method to detect large STR expansions from short-read sequencing data.
