{% set name = "itol-configs" %}
{% set version = "0.1.0" %}
{% set sha256 = "fd792f9a7965c0d574e0277cc6c66c251f1bab225610f7f0878b39890d91d9e0" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/jodyphelan/itol-configs/archive/refs/tags/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage('itol-configs', max_pin="x") }}

requirements:

  run:
    - python >=3.8

test:
  imports:
    - itol_configs
  commands:
    - itol-configs

about:
  home: https://github.com/jodyphelan/itol-configs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tool to generate itol config files

